"""Add ContactList and many-to-many relationship

Revision ID: 10b0fcdf2e7b
Revises: 
Create Date: 2025-05-28 20:10:23.136355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b0fcdf2e7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_list_membership',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('contact_list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['contact_list_id'], ['contact_list.id'], ),
    sa.PrimaryKeyConstraint('contact_id', 'contact_list_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_list_membership')
    op.drop_table('contact_list')
    # ### end Alembic commands ###
